/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Cliente;
import classes.Funcionario;
import classes.PrestadorDeServico;
import classes.CadastroProjeto;
import classes.CadastroMateriais;
import classes.Fabricante;
import classes.CadastroLevantamento;
import classes.Orcamento;
import classes.Contrato;
import javax.swing.JOptionPane;
/**
 *
 * @author Renan
 */
public class TelaEmitirRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEmitirRelatorio
     */
    public TelaEmitirRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jcTipo = new javax.swing.JComboBox<>();
        textCodigoDoRelatorio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        setClosable(true);
        setTitle("Emissão de Relatórios");
        setToolTipText("");

        jButton1.setText("Emitir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cliente", "Funcionário", "Prestador de Serviço", "Projeto", "Material", "Fabricante", "Levantamento", "Orçamento", "Contrato" }));
        jcTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Tipo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCodigoDoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCodigoDoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jcTipo.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione uma opção para Emitir o Relatório.");
        }
        else {
            if(jcTipo.getSelectedItem().equals("Cliente")) {
                Cliente cliente = new Cliente();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + cliente.toString());
            }
            if(jcTipo.getSelectedItem().equals("Funcionário")) {
                Funcionario funcionario = new Funcionario();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + funcionario.toString());
            }
            if(jcTipo.getSelectedItem().equals("Prestador de Serviço")) {
                PrestadorDeServico prestadorDeServico = new PrestadorDeServico();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + prestadorDeServico.toString());
            }
            if(jcTipo.getSelectedItem().equals("Projeto")) {
                CadastroProjeto projeto = new CadastroProjeto();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + projeto.toString());
            }
            if(jcTipo.getSelectedItem().equals("Material")) {
                CadastroMateriais material = new CadastroMateriais();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + material.toString());
            }
            if(jcTipo.getSelectedItem().equals("Fabricante")) {
                Fabricante fabricante = new Fabricante();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + fabricante.toString());
            }
            if(jcTipo.getSelectedItem().equals("Levantamento")) {
                CadastroLevantamento levantamento = new CadastroLevantamento();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + levantamento.toString());
            }
            if(jcTipo.getSelectedItem().equals("Orçamento")) {
                Orcamento orcamento = new Orcamento();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + orcamento.toString());
            }
            if(jcTipo.getSelectedItem().equals("Contrato")) {
                Contrato contrato = new Contrato();
                JOptionPane.showMessageDialog(null, "Relatório Emitido com Sucesso!\n\n" + contrato.toString());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JTextField textCodigoDoRelatorio;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
